# Purpose of this linter:
# catch bugs/issues with some things like YML, XML, JSON formatting issues
# set it to disable (not run) on things tested elsewhere (e.g. CSS and JS)
# https://github.com/github/super-linter
#
name: Super Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JSCPD: false
          VALIDATE_SHELL_SHFMT: false
